ALTER TABLE "VerificationRequest"
ALTER COLUMN "meetUrl" DROP NOT NULL,
ALTER COLUMN "verificationLink" DROP NOT NULL,
ALTER COLUMN "linkExpiresAt" DROP NOT NULL,
ALTER COLUMN "reason" DROP NOT NULL;
