ALTER TABLE "User"
  ADD COLUMN IF NOT EXISTS "isVideoVerified" BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS "videoUrl" TEXT,
  ADD COLUMN IF NOT EXISTS "onboardingToken" TEXT,
  ADD COLUMN IF NOT EXISTS "onboardingTokenExpiresAt" TIMESTAMP(3),
  ADD COLUMN IF NOT EXISTS "onboardingPaymentRef" TEXT,
  ADD COLUMN IF NOT EXISTS "onboardingPaymentVerifiedAt" TIMESTAMP(3);

CREATE UNIQUE INDEX IF NOT EXISTS "User_onboardingToken_key" ON "User"("onboardingToken");

ALTER TABLE "Photo"
  ADD COLUMN IF NOT EXISTS "cropX" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "cropY" DOUBLE PRECISION,
  ADD COLUMN IF NOT EXISTS "cropZoom" DOUBLE PRECISION;
